export const OPERATIONS = {
  'Décennale BTP': {
    icon: '🏗️',
    client: 'whd',
    fields: [
      { id: 'salaries', label: 'Nombre de salariés', type: 'number', req: true, placeholder: 'Ex. : 8' },
      { id: 'ca', label: "Chiffre d'affaires annuel (approx.)", type: 'text', req: true, placeholder: 'Ex. : 500 000 €' },
      { id: 'assureur', label: 'Assureur décennale actuel', type: 'text', req: true, placeholder: 'Ex. : Allianz, MMA, AXA...' },
      { id: 'anciennete', label: 'Depuis combien de temps ?', type: 'text', req: true, placeholder: 'Ex. : 3 ans' },
      { id: 'engagement', label: 'Engagement contractuel', type: 'radio', req: true, options: ['Libre — peut sortir quand il veut', 'Encore engagé', 'Ne sait pas'] },
      { id: 'echeance', label: "Date d'échéance", type: 'date-or-unknown', req: true },
      { id: 'sinistres', label: 'Sinistres décennaux (5 dernières années)', type: 'radio', req: true, options: ['Aucun', 'Oui — sinistres clos', 'Oui — sinistres encore ouverts'] },
      { id: 'activite_evol', label: "Évolution récente de l'activité", type: 'radio', req: true, options: ['Aucune', 'Nouvelles prestations (ITE, toiture, fondations, panneaux solaires...)', 'Changement de forme juridique'] },
      { id: 'signaux', label: 'Signaux détectés', type: 'checkboxes', req: false, options: ["Prime augmentée sans explication", "Refus de renouvellement", "Activité élargie non déclarée", "Aucun signal particulier"] },
      { id: 'motivation', label: 'Niveau de motivation', type: 'radio', req: true, options: ['Très intéressé — demande à comparer', 'Ouvert — à convaincre', 'Hésitant — objection traitée', 'RDV de convenance'] },
      { id: 'docs', label: 'Documents promis avant RDV', type: 'checkboxes', req: false, options: ['Contrat décennale actuel', 'Relevé sinistralité 3-5 ans', 'Kbis -3 mois'] },
    ],
  },
  'Télécom B2B': {
    icon: '📡',
    client: 'gconnex',
    fields: [
      { id: 'salaries', label: 'Nombre de salariés', type: 'number', req: true, placeholder: 'Ex. : 12' },
      { divider: 'Connexion internet' },
      { id: 'type_connexion', label: 'Type de connexion actuelle', type: 'radio', req: true, options: ['Fibre optique (FTTH/FTTO)', 'ADSL / VDSL', '4G/5G fixe', 'Ne sait pas'] },
      { id: 'fournisseur_internet', label: 'Fournisseur internet actuel', type: 'text', req: true, placeholder: 'Ex. : Orange, SFR, Bouygues, Free...' },
      { id: 'nb_equipements', label: 'Nb équipements connectés (approx.)', type: 'text', req: false, placeholder: 'Ex. : 15 postes' },
      { divider: 'Téléphonie mobile' },
      { id: 'operateur_mobile', label: 'Opérateur mobile actuel', type: 'radio', req: true, options: ['Orange', 'SFR', 'Bouygues', 'Free', 'Autre'] },
      { id: 'nb_lignes', label: 'Nombre de lignes mobiles', type: 'number', req: true, placeholder: 'Ex. : 6' },
      { id: 'itinerants', label: 'Collaborateurs itinérants ?', type: 'radio', req: false, options: ['Oui — régulièrement', 'Occasionnellement', 'Non'] },
      { id: 'international', label: 'Usage international (roaming) ?', type: 'radio', req: false, options: ['Oui — fréquent', 'Oui — ponctuel', 'Non'] },
      { id: 'facture_groupee', label: 'Facture groupée internet + mobile ?', type: 'radio', req: false, options: ['Oui', 'Non — séparées', 'Ne sait pas'] },
      { divider: 'Engagement et satisfaction' },
      { id: 'engagement', label: 'Engagement en cours ?', type: 'radio', req: true, options: ['Encore engagé', 'Libre de changer', 'Ne sait pas'] },
      { id: 'echeance', label: "Échéance du contrat", type: 'date-or-unknown', req: true },
      { id: 'satisfaction', label: 'Satisfaction actuelle', type: 'radio', req: true, options: ['Très satisfait', 'Satisfait avec quelques problèmes', 'Insatisfait — problèmes de débit/stabilité'] },
      { id: 'ouverture', label: 'Ouverture au changement', type: 'radio', req: true, options: ["Prêt à comparer", "Peut-être — à l'étude", "Non — renouvellement automatique prévu"] },
    ],
  },
  'RC Pro': {
    icon: '📋',
    client: null,
    fields: [
      { id: 'salaries', label: 'Nombre de salariés', type: 'number', req: true, placeholder: 'Ex. : 5' },
      { id: 'ca', label: "Chiffre d'affaires annuel", type: 'text', req: true, placeholder: 'Ex. : 200 000 €' },
      { id: 'secteur', label: "Secteur d'activité principal", type: 'text', req: true, placeholder: 'Ex. : Conseil, BTP, Informatique...' },
      { id: 'assureur_rc', label: 'Assureur RC Pro actuel', type: 'text', req: true, placeholder: 'Ex. : AXA, Generali...' },
      { id: 'engagement', label: 'Engagement contractuel', type: 'radio', req: true, options: ['Libre de changer', 'Encore engagé', 'Ne sait pas'] },
      { id: 'echeance', label: "Date d'échéance", type: 'date-or-unknown', req: true },
      { id: 'sinistres_rc', label: 'Sinistres RC sur 3 ans ?', type: 'radio', req: true, options: ['Aucun', 'Oui — clos', 'Oui — en cours'] },
      { id: 'motivation', label: 'Motivation', type: 'radio', req: true, options: ['Très intéressé', 'Ouvert', 'Hésitant'] },
    ],
  },
  'Assurance emprunteur': {
    icon: '🏠',
    client: null,
    fields: [
      { id: 'banque', label: 'Banque prêteur', type: 'text', req: true, placeholder: 'Ex. : Crédit Agricole, BNP...' },
      { id: 'montant', label: 'Montant du prêt (€)', type: 'text', req: true, placeholder: 'Ex. : 250 000 €' },
      { id: 'duree', label: 'Durée restante du prêt', type: 'text', req: true, placeholder: 'Ex. : 18 ans' },
      { id: 'type_pret', label: 'Type de prêt', type: 'radio', req: true, options: ['Immobilier résidentiel', 'Immobilier professionnel', 'Autre'] },
      { id: 'assureur_emp', label: 'Assureur emprunteur actuel', type: 'text', req: true, placeholder: 'Ex. : Banque elle-même, CNP...' },
      { id: 'motivation', label: 'Motivation', type: 'radio', req: true, options: ["Très intéressé — veut comparer", "Ouvert", "Hésitant"] },
    ],
  },
  'Véhicule professionnel': {
    icon: '🚐',
    client: null,
    fields: [
      { id: 'salaries', label: 'Nombre de salariés', type: 'number', req: true, placeholder: 'Ex. : 10' },
      { id: 'nb_vehicules', label: 'Nombre de véhicules dans la flotte', type: 'number', req: true, placeholder: 'Ex. : 4' },
      { id: 'type_vehicules', label: 'Type de véhicules', type: 'checkboxes', req: false, options: ['Voitures de fonction (VF)', 'Véhicules utilitaires légers (VUL)', 'Poids lourds', 'Mixte'] },
      { id: 'usage', label: 'Usage principal', type: 'radio', req: true, options: ['Commercial / représentation', 'Transport de marchandises', 'Chantier / BTP', 'Mixte'] },
      { id: 'mode_financement', label: 'Mode de financement actuel', type: 'radio', req: true, options: ['Achat comptant', 'Crédit / LOA', 'LLD (location longue durée)', 'Mixte'] },
      { id: 'fournisseur_vehicule', label: 'Fournisseur / loueur actuel', type: 'text', req: false, placeholder: 'Ex. : Arval, ALD, concessionnaire...' },
      { id: 'engagement', label: 'Engagement en cours ?', type: 'radio', req: true, options: ['Encore engagé', 'Libre de changer', 'Ne sait pas'] },
      { id: 'echeance', label: 'Fin de contrat / renouvellement prévu', type: 'date-or-unknown', req: true },
      { id: 'projet', label: 'Type de projet', type: 'radio', req: true, options: ['Renouvellement de flotte', 'Acquisition nouveaux véhicules', 'Passage en LLD', 'Optimisation des coûts'] },
      { id: 'motivation', label: 'Niveau de motivation', type: 'radio', req: true, options: ['Très intéressé', 'Ouvert — à convaincre', 'Hésitant'] },
    ],
  },
  'Énergie': {
    icon: '⚡',
    client: null,
    fields: [
      { id: 'salaries', label: 'Nombre de salariés', type: 'number', req: true, placeholder: 'Ex. : 15' },
      { id: 'nb_sites', label: 'Nombre de sites / locaux', type: 'number', req: true, placeholder: 'Ex. : 2' },
      { id: 'fournisseur_energie', label: 'Fournisseur énergie actuel', type: 'text', req: true, placeholder: 'Ex. : EDF, ENI, TotalEnergies...' },
      { id: 'type_contrat', label: 'Type de contrat', type: 'radio', req: true, options: ['Électricité uniquement', 'Gaz uniquement', 'Électricité + gaz', 'Ne sait pas'] },
      { id: 'engagement', label: 'Engagement contractuel', type: 'radio', req: true, options: ['Libre de changer', 'Encore engagé', 'Ne sait pas'] },
      { id: 'echeance', label: "Date d'échéance du contrat", type: 'date-or-unknown', req: true },
      { id: 'puissance', label: 'Puissance souscrite (si connue)', type: 'text', req: false, placeholder: 'Ex. : 36 kVA...' },
      { id: 'satisfaction_energie', label: 'Satisfaction actuelle', type: 'radio', req: true, options: ['Satisfait', 'Hausses de prix importantes', 'Problèmes de facturation', 'Insatisfait'] },
      { id: 'interet_panneaux', label: 'Intérêt pour le photovoltaïque ?', type: 'radio', req: false, options: ['Oui — toiture disponible', 'Peut-être', 'Non'] },
      { id: 'motivation', label: 'Niveau de motivation', type: 'radio', req: true, options: ["Très intéressé — veut comparer", "Ouvert", "Hésitant"] },
    ],
  },
};

export const OPERATION_NAMES = Object.keys(OPERATIONS);
